version: '3.8'
services:
  backend:
    image: yochambeo/back:latest
    ports:
      - '80:80'  # Cambiado a puerto 80 para coincidir con tu configuración de despliegue
    env_file:
      - /tmp/env/.env  # Usando el archivo .env descargado de S3
    command: npm run start:prod
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - /tmp/env/.env # Usando el archivo .env para la base de datos
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
